# Generated by Django 4.0.5 on 2022-07-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stdid', models.CharField(max_length=20)),
                ('stdname', models.CharField(max_length=20)),
                ('stdemail', models.EmailField(max_length=254)),
                ('stdcontact', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
